apiVersion: v1
kind: Service
metadata:
  name: prod-mongodb-service-lol-duo
  namespace: prod-lol-duo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    db: prod-lol-duo-mongodb
